# Importing the Libraries


In [1]:
# Importing the Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset

In [10]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values
print(dataset.shape, X.shape, y.shape)

print(X)
print(y)

(10, 4) (10, 3) (10,)
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# Taking care of missing data

In [11]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer()
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
print(X)

# https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html#sklearn.impute.SimpleImputer
# X[:, 1:3] = imputer.fit_transform(X[:, 1:3])


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# Encoding categorical data

In [12]:
from sklearn.preprocessing import LabelEncoder
# labelencoder_X = LabelEncoder()
# X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

print(X)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
[0 1 0 0 1 1 0 1 0 1]


# Encoding the Independent variable

In [13]:
from sklearn.preprocessing import OneHotEncoder
# onehotencoder = OneHotEncoder()
# X = onehotencoder.fit_transform(X).toarray()
# onehotencoder.categories_

In [14]:
X1 = X[:, 0].reshape(-1, 1)

onehotencoder_X1 = OneHotEncoder()
X1 = onehotencoder_X1.fit_transform(X1).toarray()
onehotencoder_X1.categories_
print(X1)

X = np.c_[X1, X[:, 1:]]
print(X)


[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


# Splitting the dataset into the Training set and Test set

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print(y_train, y_test)

[1 1 1 0 1 0 0 1] [0 0]


# Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
# x = sc_x.fit_transform(x)
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
print(X_train, X_test)

[[ 1.         -1.          2.64575131 -0.77459667 -0.37796447  0.
  -0.37796447 -0.37796447 -0.37796447 -0.37796447  2.64575131 -0.37796447
  -0.37796447  0.         -0.37796447 -0.37796447  0.         -0.37796447
  -0.37796447  2.64575131 -0.37796447 -0.37796447 -0.37796447  0.        ]
 [-1.          1.         -0.37796447 -0.77459667 -0.37796447  0.
  -0.37796447  2.64575131 -0.37796447 -0.37796447 -0.37796447 -0.37796447
  -0.37796447  0.         -0.37796447 -0.37796447  0.         -0.37796447
  -0.37796447 -0.37796447  2.64575131 -0.37796447 -0.37796447  0.        ]
 [ 1.         -1.         -0.37796447  1.29099445  2.64575131  0.
  -0.37796447 -0.37796447 -0.37796447 -0.37796447 -0.37796447 -0.37796447
  -0.37796447  0.          2.64575131 -0.37796447  0.         -0.37796447
  -0.37796447 -0.37796447 -0.37796447 -0.37796447 -0.37796447  0.        ]
 [ 1.         -1.         -0.37796447  1.29099445 -0.37796447  0.
  -0.37796447 -0.37796447 -0.37796447  2.64575131 -0.37796447 -0.37