In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import f_regression


In [2]:
NBApoints_data= pd.read_csv("NBApoints.csv")
print(NBApoints_data.shape)


(476, 30)


**資料說明**
* Pk：排名
* Player：球員
* Pos：守備位置
* Age：年齡
* Tm：隊名

In [3]:
#TODO
from sklearn.preprocessing import LabelEncoder
label_encoder_conver = LabelEncoder()
NBApoints_data["Pos"] = label_encoder_conver.fit_transform(NBApoints_data["Pos"])

label_encoder_conver = LabelEncoder()
NBApoints_data["Tm"] = label_encoder_conver.fit_transform(NBApoints_data["Tm"])


In [6]:
print(NBApoints_data.shape)
display(NBApoints_data)


(476, 30)


Rk            Player  Pos  Age  Tm   G  GS    MP    FG   FGA  ...  \
0      1     Stephen Curry    3   27   9  79  79  34.2  10.2  20.2  ...   
1      2      James Harden    5   26  10  82  82  38.1   8.7  19.7  ...   
2      3      Kevin Durant    4   27  20  72  72  35.8   9.7  19.2  ...   
3      4  DeMarcus Cousins    0   25  25  65  65  34.6   9.2  20.5  ...   
4      5      LeBron James    4   31   5  76  76  35.6   9.7  18.6  ...   
..   ...               ...  ...  ...  ..  ..  ..   ...   ...   ...  ...   
471  472        Joe Harris    5   24   5   5   0   3.0   0.2   0.8  ...   
472  473     Bruno Caboclo    4   20  27   6   1   7.2   0.2   2.0  ...   
473  474        Sam Dekker    4   21  10   3   0   2.0   0.0   0.0  ...   
474  475      J.J. O'Brien    4   23  29   2   0   3.0   0.0   0.5  ...   
475  476     Nate Robinson    3   31  18   2   1  11.5   0.0   0.5  ...   

       FT%  ORB  DRB   TRB  AST  STL  BLK  TOV   PF  PS/G▼  
0    0.908  0.9  4.6   5.4  6.7  2.1  0.2  3.3  2.0   30.1  
1    0.860  0.8  5.3   6.1  7.5  1.7  0.6  4.6  2.8   29.0  
2    0.898  0.6  7.6   8.2  5.0  1.0  1.2  3.5  1.9   28.2  
3    0.718  2.4  9.1  11.5  3.3  1.6  1.4  3.8  3.6   26.9  
4    0.731  1.5  6.0   7.4  6.8  1.4  0.6  3.3  1.9   25.3  
..     ...  ...  ...   ...  ...  ...  ...  ...  ...    ...  
471    NaN  0.0  0.6   0.6  0.4  0.0  0.0  0.2  0.2    0.6  
472    NaN  0.2  0.2   0.3  0.2  0.3  0.2  0.7  0.3    0.5  
473    NaN  0.0  0.3   0.3  0.0  0.3  0.0  0.0  0.0    0.0  
474    NaN  0.0  0.5   0.5  0.0  0.5  0.0  0.0  0.5    0.0  
475    NaN  0.0  0.0   0.0  2.0  0.5  0.0  0.0  2.5    0.0  

[476 rows x 30 columns]

In [9]:
X_train = pd.DataFrame(NBApoints_data.T, ['Pos', 'Age', 'Tm']).T
y_train = pd.DataFrame(NBApoints_data.T, ['3P']).T
y_train = np.array(y_train, dtype='float')
print(X_train.shape, y_train.shape)


(476, 3) (476, 1)


In [16]:
X = NBApoints_data.iloc[:, 2:5].values
print(X.shape)
print(X)


(476, 3)
[[ 3 27  9]
 [ 5 26 10]
 [ 4 27 20]
 ...
 [ 4 21 10]
 [ 4 23 29]
 [ 3 31 18]]


In [10]:
#TODO
NBApoints_linear_model = LinearRegression()
NBApoints_linear_model.fit(X_train, y_train)


LinearRegression()

In [11]:
NBApoints_linear_model_predict_result = NBApoints_linear_model.predict([[5, 28, 10]])
r_squared = NBApoints_linear_model.score(X_train, y_train)

print("三分球得球數=",NBApoints_linear_model_predict_result)
print("R_squared值=",r_squared)


三分球得球數= [[1.2040967]]
R_squared值= 0.25555162664371955


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


In [20]:
f_regressor = f_regression
# print("F score and p-value：", f_regressor(X_train, NBApoints_data["3P"]))
print("F score and p-value：", f_regressor(X_train, y_train))


F score and p-value： (array([151.28135474,   1.89724318,   1.14766288]), array([2.28418914e-30, 1.69037260e-01, 2.84584085e-01]))
F score and p-value： (array([151.28135474,   1.89724318,   1.14766288]), array([2.28418914e-30, 1.69037260e-01, 2.84584085e-01]))


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# statsmodels

In [13]:
import statsmodels.api as sm
X_train_c = sm.add_constant(X_train)
X_train_c = np.array(X_train_c, dtype='float')

regressor_OLS = sm.OLS(y_train, X_train_c).fit()
print(regressor_OLS.summary())


/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.256
Model:                            OLS   Adj. R-squared:                  0.251
Method:                 Least Squares   F-statistic:                     54.01
Date:                Tue, 15 Mar 2022   Prob (F-statistic):           5.00e-30
Time:                        07:18:04   Log-Likelihood:                -444.04
No. Observations:                 476   AIC:                             896.1
Df Residuals:                     472   BIC:                             912.7
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.1344      0.187     -0.720      0.4

/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/tsatools.py:117: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


In [14]:
X_opt = np.array(X_train_c[:, [0, 1, 2]], dtype='float')

regressor_OLS = sm.OLS(y_train, X_opt).fit()
print(regressor_OLS.summary())


                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.250
Model:                            OLS   Adj. R-squared:                  0.247
Method:                 Least Squares   F-statistic:                     79.03
Date:                Tue, 15 Mar 2022   Prob (F-statistic):           2.45e-30
Time:                        07:18:07   Log-Likelihood:                -445.66
No. Observations:                 476   AIC:                             897.3
Df Residuals:                     473   BIC:                             909.8
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.2138      0.182     -1.176      0.2

In [21]:
X_opt = np.array(X_train_c[:, [0, 1]], dtype='float')

regressor_OLS = sm.OLS(y_train, X_opt).fit()
print(regressor_OLS.summary())


                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.242
Model:                            OLS   Adj. R-squared:                  0.240
Method:                 Least Squares   F-statistic:                     151.3
Date:                Tue, 15 Mar 2022   Prob (F-statistic):           2.28e-30
Time:                        08:02:08   Log-Likelihood:                -448.35
No. Observations:                 476   AIC:                             900.7
Df Residuals:                     474   BIC:                             909.0
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.1922      0.049      3.893      0.0

In [22]:
X_opt = np.array(X_train_c[:, [0, 2]], dtype='float')

regressor_OLS = sm.OLS(y_train, X_opt).fit()
print(regressor_OLS.summary())


                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.004
Model:                            OLS   Adj. R-squared:                  0.002
Method:                 Least Squares   F-statistic:                     1.897
Date:                Tue, 15 Mar 2022   Prob (F-statistic):              0.169
Time:                        08:02:20   Log-Likelihood:                -513.33
No. Observations:                 476   AIC:                             1031.
Df Residuals:                     474   BIC:                             1039.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.4146      0.201      2.061      0.0

In [23]:
X_opt = np.array(X_train_c[:, [0, 3]], dtype='float')

regressor_OLS = sm.OLS(y_train, X_opt).fit()
print(regressor_OLS.summary())


                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.002
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     1.148
Date:                Tue, 15 Mar 2022   Prob (F-statistic):              0.285
Time:                        08:02:31   Log-Likelihood:                -513.70
No. Observations:                 476   AIC:                             1031.
Df Residuals:                     474   BIC:                             1040.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.7487      0.065     11.445      0.0