# Dstaset 1

In [1]:
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
import numpy as np

boston = load_boston()
y = boston.target
X = boston.data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [2]:
# Import models from sklearn
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor


In [3]:
# Instantiate each of the models you imported
tree_mod = DecisionTreeRegressor()
rf_mod = RandomForestRegressor()
ada_mod = AdaBoostRegressor()
reg_mod = LinearRegression()


In [4]:
# Fit each of your models using the training data
tree_mod.fit(X_train, y_train)
rf_mod.fit(X_train, y_train)
ada_mod.fit(X_train, y_train)
reg_mod.fit(X_train, y_train)


LinearRegression()

In [5]:
# Predict on the test values for each model
preds_tree = tree_mod.predict(X_test) 
preds_rf = rf_mod.predict(X_test) 
preds_ada = ada_mod.predict(X_test) 
preds_reg = reg_mod.predict(X_test) 


In [6]:
# Import the metrics from sklearn
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error


In [7]:
def r2(actual, preds):
    
    sse = np.sum((actual-preds)**2)
    sst = np.sum((actual-np.mean(actual))**2)
    return 1 - sse/sst

# Check solution matches sklearn
print(r2(y_test, preds_tree))
print(r2_score(y_test, preds_tree))


0.7515538250885796
0.7515538250885796


In [8]:
def mse(actual, preds):
    
    return np.sum((actual-preds)**2)/len(actual)

# Check your solution matches sklearn
print(mse(y_test, preds_tree))
print(mean_squared_error(y_test, preds_tree))


18.802035928143717
18.802035928143717


In [9]:
def mae(actual, preds):
    
    return np.sum(np.abs(actual-preds))/len(actual)

# Check your solution matches sklearn
print(mae(y_test, preds_tree))
print(mean_absolute_error(y_test, preds_tree))


2.970059880239521
2.970059880239521


In [10]:
def print_metrics(y_true, preds):

    print('Mean Squared Error: ', format(mean_squared_error(y_true, preds)))
    print('Mean Absolute Error: ', format(mean_absolute_error(y_true, preds)))
    print('R2 Score: ', format(r2_score(y_true, preds)))
    print('\n')
    

In [11]:
# Print scores
print_metrics(y_test, preds_tree)
print_metrics(y_test, preds_rf)
print_metrics(y_test, preds_ada)
print_metrics(y_test, preds_reg)


Mean Squared Error:  18.802035928143717
Mean Absolute Error:  2.970059880239521
R2 Score:  0.7515538250885796


Mean Squared Error:  10.659213275449094
Mean Absolute Error:  2.1576706586826333
R2 Score:  0.8591513825432938


Mean Squared Error:  15.14922367563988
Mean Absolute Error:  2.7696403857106158
R2 Score:  0.7998213231016922


Mean Squared Error:  20.724023437339717
Mean Absolute Error:  3.148255754816822
R2 Score:  0.7261570836552481




# Dataset 2

In [12]:
import pandas as pd
import numpy as np


data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]


In [16]:
print(X.shape, y.shape, data.shape, target.shape)
print(X)
print(data)

(506, 13) (506,) (506, 13) (506,)
[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


# Dataset 3

In [17]:
from sklearn.datasets import fetch_california_housing
housing_1 = fetch_california_housing()

from sklearn.datasets import fetch_openml
housing_2 = fetch_openml(name="house_prices", as_frame=True)

In [20]:
X1 = housing_1.data
y1 = housing_1.target

X2 = housing_2.data
y2 = housing_2.target

In [21]:
print(X1.shape, y1.shape, X2.shape, y2.shape)
print(X1)
print(X2)

(20640, 8) (20640,) (1460, 80) (1460,)
[[   8.3252       41.            6.98412698 ...    2.55555556
    37.88       -122.23      ]
 [   8.3014       21.            6.23813708 ...    2.10984183
    37.86       -122.22      ]
 [   7.2574       52.            8.28813559 ...    2.80225989
    37.85       -122.24      ]
 ...
 [   1.7          17.            5.20554273 ...    2.3256351
    39.43       -121.22      ]
 [   1.8672       18.            5.32951289 ...    2.12320917
    39.43       -121.32      ]
 [   2.3886       16.            5.25471698 ...    2.61698113
    39.37       -121.24      ]]
          Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1.0        60.0       RL         65.0   8450.0   Pave  None      Reg   
1        2.0        20.0       RL         80.0   9600.0   Pave  None      Reg   
2        3.0        60.0       RL         68.0  11250.0   Pave  None      IR1   
3        4.0        70.0       RL         60.0   9550.0   Pave  None      